// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat } from "@snaplet/copycat";
import { defineConfig } from "snaplet";

import { hashPassword } from "@calcom/features/auth/lib/hashPassword";

copycat.setHashKey("zXBAR+MWoTUaO94S");

export default defineConfig({
  generate: {
    async run(snaplet) {
      await snaplet.users([
        {
          name: "delete-me",
          email: "delete-me@example.com",
          username: "delete-me",
          password: await hashPassword("delete-me"),
          Schedule: undefined,
        },
      ]);
    },
  },
});
