// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat } from "@snaplet/copycat";
import { defineConfig } from "snaplet";

import { createUserAndEventType } from "./.snaplet/utils.ts";

copycat.setHashKey("zXBAR+MWoTUaO94S");

export default defineConfig({
  generate: {
    async run(snaplet) {
      snaplet.$pipe([
        ...(await createUserAndEventType(snaplet, {
          user: {
            email: "delete-me@example.com",
            name: "delete-me",
            password: "delete-me",
            username: "delete-me",
          },
        })),
        ...(await createUserAndEventType(snaplet, {
          user: {
            email: "onboarding@example.com",
            password: "onboarding",
            username: "onboarding",
            name: "onboarding",
            completedOnboarding: false,
          },
        })),
        ...(await createUserAndEventType(snaplet, {
          user: {
            email: "free-first-hidden@example.com",
            password: "free-first-hidden",
            username: "free-first-hidden",
            name: "Free First Hidden Example",
          },
          eventTypes: [
            {
              title: "30min",
              slug: "30min",
              length: 30,
              hidden: true,
            },
            {
              title: "60min",
              slug: "60min",
              length: 30,
            },
          ],
        })),
      ]);
    },
  },
});
